name: deploy

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Code clone
        uses: actions/checkout@v4

 
      - name: Deploy via nginx
        run: |
          sudo rm -f /usr/share/nginx/html/index.html
          sudo cp .github/workflows/index.html /usr/share/nginx/html/index.html
          sudo systemctl restart nginx


      - name: Deploy code
        run: echo "Code deployed to AWS EC2 instance"
