name: deploy

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Code clone
        uses: actions/checkout@v4

 
      - name: Deploy via nginx
        run: |
          sudo cp index.html /usr/share/nginx/html/index.html
          sudo chown root:root /usr/share/nginx/html/index.html
          sudo chmod 644 /usr/share/nginx/html/index.html
          sudo systemctl restart nginx

      - name: Deploy code
        run: echo "Code deployed to AWS EC2 instance"
